### ISSUE TITLE
Da lao Are you 整理好的 code?

### ISSUE THREAD

**Issue by LDFKILLWPF** [zhirui-gao/Deep-Template-Matching#10]
I needed you![哭哭]

**Comment by LDFKILLWPF** [comment]
I give you the star! I am happy!

**Comment by zhirui-gao** [comment]
Thanks for your interest in our work. I have reorganized the code, which includes removing redundant files, and provided training and testing scripts, along with a quick demo for testing. For more detailed information, please see the README
