### ISSUE TITLE
Does it support C++ deployment?

### ISSUE THREAD

**Issue by zhenhuamo** [zhirui-gao/Deep-Template-Matching#11]
Hello, can I support C++ deployment?

**Comment by zhirui-gao** [comment]
hi, the deep learning model can be called by C++, but we don't provide an interface for it.

**Comment by zhenhuamo** [comment]
请问，是否只能用黑白的二值图训练吗？自已采集的可以吗？

**Comment by zhirui-gao** [comment]
不一定是要求黑白二值图，这个方法核心是假设模板和待检测物体存在一个2D的单应性，满足这个假设即可。
