### ISSUE TITLE
预训练权重

### ISSUE THREAD

**Issue by JL13sky** [zhirui-gao/Deep-Template-Matching#13]
你好，某些原因，无法下载与训练权重，可以用其他方式分享吗

**Comment by JL13sky** [comment]
> 我不确定有其他方便的分享方式，或许你可以自己训练一个权重

百度网盘可以吗？好像自己训练也需要预训练权重epoch=17-auc@1=0.175-auc@3=0.591-auc@5=0.748-auc@1=auc@10=0.874.ckpt。感谢！

**Comment by zhirui-gao** [comment]
你好，代码是可以train from scratch
