### ISSUE TITLE
requirements.txt not complete

### ISSUE THREAD

**Issue by daneil86** [zhirui-gao/Deep-Template-Matching#14]
Hello,

I tried to run the test_demo.py and was struggling a bit with the installation. First it took me a while to determine the right python version. In the end I was successfull with python 3.8. Could you add this info to the readme? Then torchvision is missing in the requirements.txt. I installed 0.17.2 manually and then got an error in .\src\lightning\data.py probably because of a wrong version of torch which could be solved by replacing line 27 by:

#from torch._six import string_classes
string_classes = str

Next I got the following error:

AssertionError: Torch not compiled with CUDA enabled

That could be solved by installing torch_stable as suggested in: https://github.com/pytorch/pytorch/issues/30664

pip uninstall torch
pip cache purge
pip install torch -f https://download.pytorch.org/whl/torch_stable.html

With this its running now. Thanks a lot for sharing your work!
Daniel

**Comment by zhirui-gao** [comment]
Hi, Daniel:
Here is the torch version in my conda env, and the python version is 3.8
torch==1.13.1+cu116
torch-efficient-distloss==0.1.3
torch-scatter==2.1.1
torchaudio==0.13.1+cu116
torchmeta==1.4.0
torchmetrics==0.5.0
torchvision==0.14.1+cu116
