### ISSUE TITLE
数据格式

### ISSUE THREAD

**Issue by FPPMXB** [zhirui-gao/Deep-Template-Matching#15]
你好！  我想问一下，train_data文件夹下，points和trans存储的npy格式数据是什么含义呢?  
points文件夹下是模板图像的采样点嘛？
如果想在自己的数据集上使用，points和trans两个文件夹的npy数据应该怎样生成呢？

**Comment by zhirui-gao** [comment]
points 是模板上采样的点，trans 表示 gt(即通过这个变换矩阵可以把模板图像上的像素点与图像上对应位置的像素对齐)
如果是自己的数据集，对于模板，只需要采样即可，最好能均匀采样表达出模板的形状（最远点采样），而npy文件就是监督学习的gt，看你怎么生成训练数据，需要按生成的方法保存对应的变换矩阵。
