### ISSUE TITLE
模版生成

### ISSUE THREAD

**Issue by xuleiaa** [zhirui-gao/Deep-Template-Matching#16]
您好，请问您使使用什么方法生成模版的，我使用自己的方法生成的模版是不够理想的，能提供一下生成脚本或方法吗，万分感谢

**Comment by zhirui-gao** [comment]
请问是得到mask的图像吗？这个需要你有对应的gt才能得到的，能看看你目前生成的模板吗？

**Comment by xuleiaa** [comment]
我们是希望得到用于训练二值模版图像，我们使用一些图像处理技术去生成，发现这种方法生成的二值模版是糟糕的。而且我们在test_demo.py中使用您的预训练模型去测试一些简单的数据，得到如图的效果，我们对此感到十分困惑的，希望大佬能解释一下原因

![Figure_1](https://github.com/user-attachments/assets/456dda76-0c60-4d61-af9d-6576e10cf8ed)

!

**Comment by zhirui-gao** [comment]
匹配数据生存的问题，在前提我们尝试过手动标注一些图像的mask，然后使用一些数据增强的方式来增大数据量。后来正如论文所说的，采用了GauGan来生成更多的工业匹配数据。此外，我觉得采用一些分割算法，加上数据增强也能得到数据来训练。
您测试的这组例子，我不确定是否开启了边缘检测模块（是需要的），如果依然存在问题，您能把原始数据法我一份测试一下吗？
