### ISSUE TITLE
Environment.yml not included

### ISSUE THREAD

**Issue by littlebeanhp** [zhirui-gao/Deep-Template-Matching#2]
Hello,

I cannot find the environment.yml you mentioned in readme. Any helps with this?

Thank you

**Comment by zhirui-gao** [comment]
Hi, thanks for your interest in our work.
For convenience, I suggest you can follow the environment in the [LoFTR](https://github.com/zju3dv/LoFTR). The environment requirements of the two are similar.
best wishes.

**Comment by Original-Adios** [comment]
File "Deep-Template-Matching/pidinet/edge_net.py", line 8, in <module>
    import models
ModuleNotFoundError: No module named 'models'

**Comment by zhirui-gao** [comment]
> 

I have added required files to this repo from [pidinet](https://github.com/hellozhuo/pidinet)
