### ISSUE TITLE
Running the demo

### ISSUE THREAD

**Issue by tobibaum** [zhirui-gao/Deep-Template-Matching#3]
Dear @zhirui-gao ,

thanks for sharing this great work. I am very interested in trying it for my current research. I would like to run your `demo_single_pair.ipynb` but I believe I am missing some prerequisites.
What exactly is the code in `Template_Matching_v5_loftr`?
When I download a vanilla version of LoFTR from https://github.com/zju3dv/LoFTR, I am missing some modules:
```
      4 os.chdir('/home/tobi/apps/LoFTR')
----> 5 from src.lightning.lightning_tm import PL_Tm
      6 from src.config.default import get_cfg_defaults
      7 import torch

ModuleNotFoundError: No module named 'src.lightning.lightning_tm'
```

do you have the checkpoint `epoch=17-auc@1=0.175-auc@3=0.591-auc@5=0.748-auc@1=auc@10=0.874.ckpt` available for download somewhere?

Thanks!!

**Comment by zhirui-gao** [comment]
Hi,
The checkpoint  is available [link](https://drive.google.com/file/d/1__Az9VqbLy28TAosnHpNJJLrQEGQ4pAJ/view?usp=drive_link)
"Template_Matching_v5_loftr" is the directory of this project, which means . you need use "Deep-Template-Matching" instead.
There is no need to download the LoFTR.

**Comment by tobibaum** [comment]
Hey,

Thank you for the `ckpt` and the super fast response!! I am having some trouble loading the file. Running the notebook as is causes the file `edge_dataloader.py` to be missing. I added a PYTHONPATH to a fresh `pidinet` repo to find that file. still, I am getting some errors.

In [`pidinet/edge_net.py`:L10](https://github.com/zhirui-gao/Deep-Template-Matching/blob/master/pidinet/edge_net.py#L10) you load utils
```
from utils import *
```

which utils is meant here? The one from the pidinet repo fails with
```
Deep-Template-Matching/pidinet/edge_net.py:83, in Edge_Net.__init__(self, config)
     81 args = Arg()
     82 self.model = getattr(models, config['name'])(args)
---> 83 checkpoint = load_checkpoint(args)
     84 if args.evaluate_converted:
     85     state_dict = convert_pidinet(checkpoint['state_dict'], args.config)

TypeError: load_checkpoint() missing 1 required positional argument: 'running_file'
```

Using the `utils.py` from `src/utils/` fails with:
```
Deep-Template-Matching/src/utils/utils.py:134, in load_checkpoint(load_path, filename)
    132 filename = '{}__{}'.format(file_prefix[0], filename)
    133 # torch.save(net_state, save_path)
--> 134 checkpoint = torch.load(load_path/filename)
    135 print("load checkpoint from ", filename)
    136 return checkpoint

TypeError: unsupported operand type(s) for /: 'Arg' and 'str'
```

which function `load_checkpoint` from which `utils.py` should be loaded here?

Thank you very much!!!

**Comment by tobibaum** [comment]
Ok. I got it to work using the `load_checkpoint` function from pidinet (you'll have to download your own copy of pidinet)
