### ISSUE TITLE
how to train my own datasets?

### ISSUE THREAD

**Issue by hahans** [zhirui-gao/Deep-Template-Matching#6]
I can't find the './own_dataset' folder.Could you please give me some examples  of  dataset format.

**Comment by zhirui-gao** [comment]
Thank you for your interest in our work, and sorry for the trouble, we will organize our code later!

**Comment by zhirui-gao** [comment]
I have organized the code and  provided  the examples of dataset format in './data/train_data'

**Comment by hahans** [comment]
ok



发自我的iPhone


------------------ Original ------------------
From: gzrer ***@***.***&gt;
Date: Wed,Mar 20,2024 5:22 PM
To: zhirui-gao/Deep-Template-Matching ***@***.***&gt;
Cc: Fisheries Expert ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [zhirui-gao/Deep-Template-Matching] how to train my own datasets?(Issue #6)





 
I have organized the code and  provided  the examples of dataset format in './data/train_data'
