### ISSUE TITLE
your work is great,but your code is piece of shit

### ISSUE THREAD

**Issue by hahans** [zhirui-gao/Deep-Template-Matching#7]
哥们你的代码跟屎一样，根本看不懂从什么地方下手进行训练。文件和文件夹之间一点分类都没，前后关系都没整好，比我同学的内裤还脏乱。还有你那个代码运行起来一堆错误，你pidinet要抄就全部抄，抄一点少一点和goushi一样。

**Comment by zhirui-gao** [comment]
Sorry，the previous code release was too rushed. We'll organize the code around December
